#!/usr/bin/env python3
import argparse
import csv
import matplotlib.pyplot as plt
import sys
import collections

def main():
    parser = argparse.ArgumentParser(description="Plot touch debug data")
    parser.add_argument("file", help="Path to the CSV file generated by TOUCH_DEBUG or TOUCH_CALIBRATE")
    args = parser.parse_args()

    # Data structure: touch_id -> list of samples
    touches = collections.defaultdict(list)

    try:
        with open(args.file, 'r') as f:
            reader = csv.DictReader(f)
            headers = reader.fieldnames
            
            has_touch_id = "TouchID" in headers
            
            for row in reader:
                sample = {
                    'time': float(row['Time']),
                    'frequency': float(row['Frequency']),
                    'z': float(row['Z']) if row.get('Z') else None,
                    'threshold': int(row['Threshold']) if 'Threshold' in row else None
                }
                
                touch_id = row['TouchID'] if has_touch_id else "1"
                touches[touch_id].append(sample)
                
    except Exception as e:
        print(f"Error reading file: {e}")
        sys.exit(1)

    if not touches:
        print("No data found in file")
        sys.exit(1)

    print(f"Found {len(touches)} touch events.")

    # If too many touches, maybe just plot the first few or ask user?
    # For now, let's plot them all but maybe in subplots if there are many?
    # Or just overlay them aligned by trigger time?
    # Let's just plot them sequentially for now, or if single touch, detailed view.

    if len(touches) == 1:
        plot_single_touch(list(touches.values())[0])
    else:
        plot_multiple_touches(touches)

def plot_single_touch(samples):
    times = [s['time'] for s in samples]
    frequencies = [s['frequency'] for s in samples]
    z_positions = [s['z'] for s in samples]
    
    # Normalize time
    start_time = times[0]
    times = [t - start_time for t in times]

    fig, ax1 = plt.subplots(figsize=(10, 6))

    color = 'tab:blue'
    ax1.set_xlabel('Time (s)')
    ax1.set_ylabel('Frequency (Hz)', color=color)
    ax1.plot(times, frequencies, color=color, label='Frequency')
    ax1.tick_params(axis='y', labelcolor=color)
    ax1.grid(True)

    if any(z is not None for z in z_positions):
        ax2 = ax1.twinx()
        color = 'tab:red'
        ax2.set_ylabel('Z Position (mm)', color=color)
        valid_z = [(t, z) for t, z in zip(times, z_positions) if z is not None]
        if valid_z:
            z_times, z_vals = zip(*valid_z)
            ax2.plot(z_times, z_vals, color=color, linestyle='--', label='Z Position')
            ax2.tick_params(axis='y', labelcolor=color)

    title = "Touch Probe Frequency vs Time"
    if samples[0]['threshold']:
        title += f" (Threshold: {samples[0]['threshold']})"
    plt.title(title)
    fig.tight_layout()
    plt.show()

def plot_multiple_touches(touches):
    # Create a figure with subplots if reasonable, or just one big plot with many lines
    # Let's try to align them by the "stop" event? Hard to know where stop is without analysis.
    # Let's just plot them in a grid.
    
    num_touches = len(touches)
    cols = 3
    rows = (num_touches + cols - 1) // cols
    
    fig, axes = plt.subplots(rows, cols, figsize=(15, 5 * rows), constrained_layout=True)
    axes = axes.flatten() if num_touches > 1 else [axes]
    
    sorted_ids = sorted(touches.keys(), key=lambda x: int(x) if x.isdigit() else x)
    
    for i, touch_id in enumerate(sorted_ids):
        if i >= len(axes): break
        
        samples = touches[touch_id]
        ax = axes[i]
        
        times = [s['time'] for s in samples]
        frequencies = [s['frequency'] for s in samples]
        
        # Normalize time
        start_time = times[0]
        times = [t - start_time for t in times]
        
        ax.plot(times, frequencies, label='Freq')
        ax.set_title(f"Touch {touch_id} (Thresh: {samples[0]['threshold']})")
        ax.grid(True)
        
        # Optional: Plot Z on secondary axis? Might be too cluttered for small subplots.
    
    # Hide unused subplots
    for i in range(num_touches, len(axes)):
        axes[i].axis('off')
        
    plt.suptitle(f"Touch Calibration Events ({num_touches} touches)")
    plt.show()

if __name__ == "__main__":
    main()
